language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "4.3.2"
notifications:
  email:
    - backstage1@corp.globo.com
  slack:
    secure: HerVthx+d5fELXWoUjmK896uPPbkKCyFKjtYiSn3h88UbECPrAwRltZhuxD7t+NGt4fcCD/aiEdem5cBTKTNZxPCNAjvBZMx7REnk0QeHL9QPardS1BA1a+o02ne25vJcd7indc7UqscUmfvEvFugXEhiHaf8Nf3e0OYk5oCx0I=
